#!/usr/bin/env bash
# install nginx on web-01

find="^\tlocation / {"
replace="\tlocation /redirect_me {\n\t\treturn 301 \@scheme://youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"

sudo apt-get -y update
sudo apt-get install -y nginx
sudo rm /var/www/html/*.html
sudo echo "Hello World" | sudo tee /var/www/html/index.html
sudo sed -i "s|$find|$replace|" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload