#!/usr/bin/env bash
# Install nginx on your web-01 server

find="^\tlocation / {"
replace="\terror_page 404 /404.html;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"

sudo apt-get -y update
sudo apt-get install -y nginx
sudo rm /var/www/html/*.html
sudo echo "Hello World" | sudo tee /var/www/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i "s|$find|$replace|" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload